### meteoPATH GUI-visualisation screen
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataapp.ui'
#
# Created: Thu Jan 10 00:12:57 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(484, 853)
        Dialog.setStyleSheet("background-color: rgb(167, 238, 244);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 70, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(55)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label.setPixmap(QtGui.QPixmap('img\loc.png'))
        self.textBrowser_2 = QtWidgets.QLabel(Dialog)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setGeometry(QtCore.QRect(150, 180, 321, 141))
        self.textBrowser_2.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(205, 255, 252);")
        self.textBrowser_2.setAlignment(QtCore.Qt.AlignCenter)
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_6 = QtWidgets.QLabel(Dialog)
        self.textBrowser_6.setWordWrap(True)
        self.textBrowser_6.setGeometry(QtCore.QRect(50, 360, 281, 181))
        font.setPointSize(24)
        self.textBrowser_6.setFont(font)
        self.textBrowser_6.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(255, 153, 153);")
        self.textBrowser_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 180, 101, 101))
        self.label_2.setObjectName("label_2")
        self.label_2.setPixmap(QtGui.QPixmap('img\Twitter_Logo_white.png'))
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(110, 0, 311, 71))
        self.label_3.setObjectName("label_3")
        self.label_3.setPixmap(QtGui.QPixmap('img\waves.png'))
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(150, 150, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 330, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.toolButton = QtWidgets.QToolButton(Dialog)
        self.toolButton.setGeometry(QtCore.QRect(300, 420, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setWeight(75)
        font.setBold(True)
        self.toolButton.setFont(font)
        self.toolButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 175, 190);")
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName("toolButton")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 570, 141, 271))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(189,183,107);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(170, 570, 141, 271))
        self.label_7.setWordWrap(True)
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(189,183,107);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(320, 570, 141, 271))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(189,183,107);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(140, 80, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.toolButton.setText(QtWidgets.QApplication.translate("Dialog", "Add New Suggestion", None))

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "meteoPATH visualisation", None))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Twitter Positivity", None))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Recomended activity", None))
        self.toolButton.setText(QtWidgets.QApplication.translate("Dialog", "Add New Suggestion", None))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "4", None))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "4", None))
        self.label_8.setText(QtWidgets.QApplication.translate("Dialog", "4", None))